.Dd May 7, 2023
.Dt WTR 1
.Os
.Sh NAME
.Nm wtr
.Nd Work Time Recorder Client
.Sh SYNOPSIS
.Nm
.Op Ar option
.Op Ar command
.Nm
.Cm add
.Ar duration
.Cm to
.Ar project
.Op Ar when
.Nm
.Cm remove
.Ar duration
.Cm from
.Ar project
.Op Ar when
.Nm
.Cm active
.Nm
.Cm edit
.Nm
.Cm list hosts
.Nm
.Cm list projects
.Nm
.Ar report
.Nm
.Cm graph
.Ar time-span
.Nm
.Cm merge
.Ar filename
.Sh DESCRIPTION
The
.Nm
utility query and update the
.Xr wtrd 1
database.
.Pp
The options are as follows:
.Bl -tag -width xxxxxxxxxxx
.It Fl d , Fl \-debug
Generate debug output.
.El
.Pp
Multiple commands are supported:
.Bl -tag -width "remove"
.It Cd add
Add some
.Ar duration
to a
.Ar project
at the beginning of the specified
.Ar moment
(now if no
.Ar moment
is provided).
.Pp
.Nm Cm add Ar duration Cm to Ar project Op Ar moment
.It Cd remove
Remove some
.Ar duration
from a
.Ar project
at the beginning of the specified
.Ar moment
(now if no
.Ar moment
is specified).
.Pp
.Nm Cm remove Ar duration Cm to Ar project Op Ar moment
.It Cd active
List active projects.
.It Cd edit
Edit
.Xr wtrd 1
configuration file.
.It Cd list
List known hosts or projects that can be used for filtering.
.Pp
.Nm Cm list Cm hosts
.br
.Nm Cm list Cm projects
.It Ar report
Report time spent on project. See the REPORTS section bellow.
.It Cd graph
Show a visual representation of the time spent on projects in a calendar.
.It Cd merge
Merge the time spent on projects in the
.Ar filename
database. Useful to track your working time on multiple nodes.
.El
.Sh REPORTS
Multiple reports syntax are accepted:
.Bl -bullet -compact
.It
.Cm today
.It
.Cm yesterday
.It
.Cm tomorrow
.It
.Cm on
.Ar date
.It
.Ar n
.Cm days ago
.It
.Cm in
.Ar n
.Cm days
.It
.Cm last
.Ar n
.Cm days
.It
.Cm next
.Ar n
.Cm days
Note: current day is not included
.It
.Cm this week
.It
.Cm last week
.It
.Cm next week
.It
.Ar n
.Cm weeks ago
.It
.Cm in
.Ar n
.Cm weeks
.It
.Cm last
.Ar n
.Cm weeks
Note: current week is not included
.It
.Cm next
.Ar n
.Cm weeks
.It
.Cm this month
.It
.Cm last month
.It
.Cm next month
.It
.Ar n
.Cm months ago
.It
.Cm in
.Ar n
.Cm months
.It
.Cm last
.Ar n
.Cm months
Note: current month is not included.
.It
.Cm next
.Ar n
.Cm months
.It
.Cm this quarter
.It
.Cm last quarter
.It
.Cm next quarter
.It
.Ar n
.Cm quarters ago
.It
.Cm in
.Ar n
.Cm quarters
.It
.Cm last
.Ar n
.Cm quarters
Note: current quarter is not included.
.It
.Cm next
.Ar n
.Cm quarters
.It
.Cm this year
.It
.Cm last year
.It
.Cm next year
.It
.Ar n
.Cm years ago
.It
.Cm in
.Ar n
.Cm years
.It
.Cm last
.Ar n
.Cm years
Note: current year is not included.
.It
.Cm next
.Ar n
.Cm years
.El
Alternatively, a start date and an end date can be passed:
.Bl -bullet -compact
.It
.Cm since
.Ar date
.It
.Cm until
.Ar date
Note:
.Ar date
is not included.
.El
In any case, a report can be split in smaller chunks with:
.Bl -bullet -compact
.It
.Cm by day
.It
.Cm by week
.It
.Cm by month
.It
.Cm by quarter
.It
.Cm by year
.El
One can also round reported times to the next (upper) invoiced fraction:
.Bl -bullet -compact
.It
.Cm rounding
.Ar duration
.El
Last, reports can be filtered to only show one or some projects or hosts:
.Bl -bullet -compact
.It
.Cm on
.Ar project ...
.It
.Cm on host
.Ar host ...
.El
.Sh DURATIONS
Multiple duration formats are supported:
.Bl -bullet -compact
.It
.Ar hrs\c
.Cm :\c
.Ar min\c
.Cm :\c
.Ar sec
.It
.Ar hrs\c
.Cm :\c
.Ar min
.It
.Ar sec
.It
.Ns
.Ar hrs\c
.Cm hrs
.It
.Ar min\c
.Cm min
.It
.Ar sec\c
.Cm sec
.El
.Sh SEE ALSO
.Xr wtrd 1 .
.Sh AUTHORS
.An Romain Tartière Aq romain@blogreen.org
