.Dd May 7, 2023
.Dt WTR 1
.Os
.Sh NAME
.Nm wtr
.Nd Work Time Recorder
.Sh SYNOPSIS
.Nm
.Cm add
.Ar duration
.Cm to
.Ar project
.Op Ar when
.Nm
.Cm remove
.Ar duration
.Cm from
.Ar project
.Op Ar when
.Nm
.Cm active
.Nm
.Cm edit
.Nm
.Cm list
.Nm
.Ar report
.Nm
.Cm graph
.Ar time-span
.Sh DESCRIPTION
The
.Nm
utility query and update the
.Xr wtrd 1
database.
.Pp
Multiple commands are supported:
.Bl -tag -width "remove" -compact
.It Cd add
Add
.Ar duration
to
.Ar project .
.It Cd remove
Remove
.Ar duration
from
.Ar project .
.It Cd active
List active projects.
.It Cd edit
Edit
.Xr wtrd 1
configuration file.
.It Cd list
List known projects.
.It Ar report
Report time spent on project. See the REPORTS section bellow.
.It Cd graph
Show a visual representation of the time spent on projects in a calendar.
.Sh REPORTS
Multiple reports syntax are accepted:
.Bl -bullet -compact
.It
.Cm today
.It
.Cm yesterday
.It
.Ar n
.Cm days ago
.It
.Cm last
.Ar n
.Cm days
Note: current day is not included
.It
.Cm this week
.It
.Cm last week
.It
.Ar n
.Cm weeks ago
.It
.Cm last
.Ar n
.Cm weeks
Note: current week is not included
.It
.Cm this month
.It
.Cm last month
.It
.Ar n
.Cm months ago
.It
.Cm last
.Ar n
.Cm months
Note: current month is not included.
.El
Alternatively, a start date and an end date can be passed:
.Bl -bullet -compact
.It
.Cm since
.Ar date
.It
.Cm until
.Ar date
Note:
.Ar date
is not included.
.El
In any case, a report can be split in smaller chunks with:
.Bl -bullet -compact
.It
.Cm by day
.It
.Cm by week
.It
.Cm by month
.El
One can also round reported times to the next (upper) invoiced fraction:
.Bl -bullet -compact
.It
.Cm rounding
.Ar duration
.El
Last, reports can be filtered to only show one or some projects or hosts:
.Bl -bullet -compact
.It
.Cm on
.Ar project ...
.It
.Cm on host
.Ar host ...
.El
.Sh DURATIONS
Multiple duration formats are supported:
.Bl -bullet -compact
.It
.Ar hrs\c
.Cm :\c
.Ar min\c
.Cm :\c
.Ar sec
.It
.Ar hrs\c
.Cm :\c
.Ar min
.It
.Ar sec
.It
.Ns
.Ar hrs\c
.Cm hrs
.It
.Ar min\c
.Cm min
.It
.Ar sec\c
.Cm sec
.El
.Sh SEE ALSO
.Xr wtrd 1 .
.Sh AUTHORS
.An Romain Tartière Aq romain@blogreen.org
